/* eslint-disable @next/next/no-sync-scripts */
import Head from 'next/head'
import WeasleyBracket from '../src/WeasleyBracket'

declare global {
  interface Window {
    bracketsViewer?: any;
  }
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <WeasleyBracket />
      </main>
    </>
  )
}
